// I have to revise these concepts
// undefined
// null
// NaN
// "" empty string

// we also learned convert to the different data types
// trim length wagera wagera string functions 

//if else..
// if(a)  we can write directly instead of writing complete if signature


// Object.keys(person) it will print the all keys of the object
// Object.values(person) it will print the all values of the object

// person.hasOwnProperty('fullname') if it has this key it will return else it will not give any error

// let fullname="Muhammad Malook";
// let city = "Ghotki";
// let state = "Sindh";
// let address = `${fullname} lives in ${city}, ${city}, ${state}`;


// let address2 = `${1 == 1}` // we can also call the function inside the backtiks
// I have to learn all about backtiks or template literal.
// I have to learn difference between framework and liberary
// imperative and procedural



// nested object
// person = {
//     name: "bilal",


//    keyOfchild: {
//         name: "sajjad",
//         keyOfchild2: {
//             name: "sajjad's child",


//         }
//     }
// }

// have to learn about nested array

// console.log(etc) // this is reference error we did not declared etc

// there are also range errors when we try to access a vriable which out of scope

// abc.etc here iam trying to access the property of object which object and property both are not defined it will show type error

// reference error
// type error
// range error
// syntax error


// try{
//     throw new TypeError("This is a type error generated by bilal");
// }
// catch(e){
//         console.log(e);
// }
// finally{
//     console.log("ye to lazmi chalega")
// }

// I have to learn complete debuging in browser's console

// setTimeout() it will take fuction as argument

//     setTimeout(()=>{
//         alert("wawawawa");
//         },5000);
// ye 5 sec ka bad ek daffa  call hoga bs



// setInterval(()=>{
//     alert("wawawawa");
//     },5000);
// ye har 5 sec k badd call hota rahega khud hi




//above both functions call also return id when we want to stop them we will call clearInterval( id ; 
// it will take id as argument


